### ISSUE TITLE
Players are not receiving reputation gains.

### ISSUE THREAD

**Issue by Conflagrated** [jcornwellshiel/uvvillagers#29]
MCPC+ 244 - 1.4.7 r1.1
Feed The Beast: Ultimate 

No matter how many mobs players kill, in siege or out, they only gain a single reputation point at random intervals (passive rep gain?). 

I've tried removing all mob related mods from the server, but it still fails to grant players their reputation rewards. Making moving up ranks and receiving payment difficult.

Edit:
Prism might have something to do with it: http://pastebin.com/mdsJbJwh 
I see similar errors any time there's a siege players are taking part in. 

I know that UVV is tracking kills, though: 

19:42:57 [INFO]  - UVVillagers Siege Info -
19:42:57 [INFO] Zombie Siege Stats:
19:42:57 [INFO]  - Location: Pompett
19:42:57 [INFO]  - Enemies: 18 (12 still alive)
19:42:57 [INFO]  - Player Kills:
19:42:57 [INFO]    - Felicrux: 6

This is weird.

**Comment by jcornwellshiel** [comment]
Thanks. I'll take a look tonight.

**Comment by jcornwellshiel** [comment]
You are correct. Trying to isolate the issue.

**Comment by jcornwellshiel** [comment]
Hah. I'm a dumbass. Reading the wrong property name from the configs. Fixing in the next update.

**Comment by Conflagrated** [comment]
Thanks a bunch, mate! Will you release 1.4.7 and 1.5 versions like last time?

**Comment by jcornwellshiel** [comment]
I certainly can.
