### ISSUE TITLE
Sometimes a village should "belong" to the server

### ISSUE THREAD

**Issue by robyxx** [jcornwellshiel/uvvillagers#42]
It would be nice if one could "fix" a villages existence and name - regardless of players popularity.
Sometimes the server admin would like for something that's recognized as a village to keep it's name, because it's a server structure.

**Comment by jcornwellshiel** [comment]
Will add to the next sprint to-do.

## 

James

**Comment by Tsubashi** [comment]
Seems like this one has been fixed, as far as I can tell. (/uvv setserver)

**Comment by jcornwellshiel** [comment]
Indeed it has. I just got really lax in commits and issues a while back.
