### ISSUE TITLE
[SEVERE] Could not pass event ... to UVVillagers v1.3.2

### ISSUE THREAD

**Issue by GraceSites** [jcornwellshiel/uvvillagers#47]
After updating to the dev build for 1.6.4, i get all sorts of errors upon login and moving,etc.  here's the logs:

http://pastebin.com/vyBLhEXs

**Comment by Tsubashi** [comment]
These errors continue in 1.7.2, though from a user perspective it seems to work.

**Comment by jcornwellshiel** [comment]
This was a separate issue in 1.7.2 introduced by an attempted fix to mayor movement. It's been resolved in version 1.3.7.
